USE reactorlabs_2018_02_01;

#DROP TABLE REPOS_QUEUE;
CREATE TABLE REPOS_QUEUE (
	REPOSITORY 	VARCHAR(255) NOT NULL,
    BRANCH 			VARCHAR(255),
    CHECKOUT_ID 	VARCHAR(255),
    RESULT 				VARCHAR(255),
    COMPLETED 		BOOLEAN DEFAULT FALSE
);

#DROP TABLE FILE_HASH_HEAD;
CREATE TABLE FILE_HASH_HEAD (
    BRANCH 		VARCHAR(255) NOT NULL,
	GIT_PATH 		VARCHAR(255) NOT NULL,
    HASH_CODE 	VARCHAR(255) NOT NULL
);

#DROP TABLE FILE_HASH_HISTORY;
CREATE TABLE FILE_HASH_HISTORY (
    BRANCH 			VARCHAR(255) NOT NULL,
	GIT_PATH 			VARCHAR(255) NOT NULL,
    HASH_CODE 		VARCHAR(255) NOT NULL,
    COMMIT_ID 		VARCHAR(255) NOT NULL,
    COMMIT_TIME 	LONG NOT NULL
);

SET SQL_SAFE_UPDATES = 0;
UPDATE REPOS_QUEUE 
SET COMPLETED = TRUE,
		CHECKOUT_ID = NULL
WHERE CHECKOUT_ID = 'dd';


SELECT REPOSITORY + ":" + BRANCH AS REPOS
FROM REPOS_QUEUE
WHERE COMPLETED = FALSE
	  AND CHECKOUT_ID IS NULL;
      


SELECT * FROM REPOS_QUEUE;
#TRUNCATE TABLE REPOS_QUEUE;