DROP TABLE IF EXISTS REPOS_QUEUE;

CREATE TABLE REPOS_QUEUE (
	REPO_OWNER 	VARCHAR(50) NOT NULL,
	REPOSITORY 	VARCHAR(50) NOT NULL,
    CHECKOUT_ID VARCHAR(13),
    RESULT 		VARCHAR(255),
    COMPLETED 	BOOLEAN DEFAULT FALSE,
--    PRIMARY KEY (REPO_OWNER, REPOSITORY),
    INDEX IDX_REPOS_QUEUE_COMPLETED (COMPLETED)
)
ROW_FORMAT=COMPRESSED
KEY_BLOCK_SIZE=8;